// Generated by make-pins.py, do NOT edit!
/*
 * Copyright (c) 2015-2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 
Q(AD_04)
Q(AD_26)
Q(AF0_LPUART1)
Q(AF10_GPIO9)
Q(AF1_LPSPI2)
Q(AF1_LPUART8)
Q(AF3_GPT2)
Q(AF4_PWM1)
Q(AF4_PWM2)
Q(AF5_GPIO3)
Q(LED1)
Q(LED2)
