// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.18-omv-0-gca3d3e947"
#define MICROPY_GIT_HASH "<no hash>"
#define OPENMV_GIT_TAG "v4.3.0-0-g20b98f02"
#define OPENMV_GIT_HASH "<no hash>"
#define MICROPY_BUILD_DATE "2023-09-12"
