/*
 * Copyright (c) 2006-2018, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2019-04-29     tyustli      first version
 */
QDEF(MP_QSTR___bool__, (const byte*)"\x2b\x65\x08" "__bool__")
QDEF(MP_QSTR___len__, (const byte*)"\xe2\xb0\x07" "__len__")
QDEF(MP_QSTR___hash__, (const byte*)"\xf7\xc8\x08" "__hash__")
QDEF(MP_QSTR___int__, (const byte*)"\x16\x1b\x07" "__int__")
QDEF(MP_QSTR___pos__, (const byte*)"\x29\xf0\x07" "__pos__")
QDEF(MP_QSTR___neg__, (const byte*)"\x69\xd5\x07" "__neg__")
QDEF(MP_QSTR___invert__, (const byte*)"\xf7\x77\x0a" "__invert__")
QDEF(MP_QSTR___abs__, (const byte*)"\x95\xd6\x07" "__abs__")
QDEF(MP_QSTR___sizeof__, (const byte*)"\x09\x3b\x0a" "__sizeof__")
QDEF(MP_QSTR___eq__, (const byte*)"\x71\x3e\x06" "__eq__")
QDEF(MP_QSTR___lt__, (const byte*)"\x5d\x68\x06" "__lt__")
QDEF(MP_QSTR___gt__, (const byte*)"\xb6\x82\x06" "__gt__")
QDEF(MP_QSTR___le__, (const byte*)"\xcc\x13\x06" "__le__")
QDEF(MP_QSTR___ge__, (const byte*)"\xa7\x46\x06" "__ge__")
QDEF(MP_QSTR___ne__, (const byte*)"\x0e\x0b\x06" "__ne__")
QDEF(MP_QSTR___iadd__, (const byte*)"\x6d\x4a\x08" "__iadd__")
QDEF(MP_QSTR___isub__, (const byte*)"\x08\x78\x08" "__isub__")
QDEF(MP_QSTR___imul__, (const byte*)"\x18\xce\x08" "__imul__")
QDEF(MP_QSTR___imatmul__, (const byte*)"\xc0\x6e\x0b" "__imatmul__")
QDEF(MP_QSTR___ifloordiv__, (const byte*)"\x4f\x0f\x0d" "__ifloordiv__")
QDEF(MP_QSTR___itruediv__, (const byte*)"\x21\x02\x0c" "__itruediv__")
QDEF(MP_QSTR___imod__, (const byte*)"\x4a\x86\x08" "__imod__")
QDEF(MP_QSTR___ipow__, (const byte*)"\x84\xd5\x08" "__ipow__")
QDEF(MP_QSTR___ior__, (const byte*)"\xf1\x8f\x07" "__ior__")
QDEF(MP_QSTR___ixor__, (const byte*)"\x09\xb9\x08" "__ixor__")
QDEF(MP_QSTR___iand__, (const byte*)"\xa7\x21\x08" "__iand__")
QDEF(MP_QSTR___ilshift__, (const byte*)"\x80\xa2\x0b" "__ilshift__")
QDEF(MP_QSTR___irshift__, (const byte*)"\xde\xf8\x0b" "__irshift__")
QDEF(MP_QSTR___add__, (const byte*)"\xc4\x82\x07" "__add__")
QDEF(MP_QSTR___sub__, (const byte*)"\x21\x09\x07" "__sub__")
QDEF(MP_QSTR___mul__, (const byte*)"\x31\x42\x07" "__mul__")
QDEF(MP_QSTR___matmul__, (const byte*)"\x49\xf3\x0a" "__matmul__")
QDEF(MP_QSTR___floordiv__, (const byte*)"\x46\x5f\x0c" "__floordiv__")
QDEF(MP_QSTR___truediv__, (const byte*)"\x88\xef\x0b" "__truediv__")
QDEF(MP_QSTR___mod__, (const byte*)"\x63\x37\x07" "__mod__")
QDEF(MP_QSTR___divmod__, (const byte*)"\x78\x11\x0a" "__divmod__")
QDEF(MP_QSTR___pow__, (const byte*)"\x2d\x00\x07" "__pow__")
QDEF(MP_QSTR___or__, (const byte*)"\x38\xbb\x06" "__or__")
QDEF(MP_QSTR___xor__, (const byte*)"\x20\xec\x07" "__xor__")
QDEF(MP_QSTR___and__, (const byte*)"\x0e\xdb\x07" "__and__")
QDEF(MP_QSTR___lshift__, (const byte*)"\x09\x88\x0a" "__lshift__")
QDEF(MP_QSTR___rshift__, (const byte*)"\x57\x98\x0a" "__rshift__")
QDEF(MP_QSTR___radd__, (const byte*)"\x16\xc5\x08" "__radd__")
QDEF(MP_QSTR___rsub__, (const byte*)"\x73\x77\x08" "__rsub__")
QDEF(MP_QSTR___rmul__, (const byte*)"\x63\x01\x08" "__rmul__")
QDEF(MP_QSTR___rmatmul__, (const byte*)"\xdb\x03\x0b" "__rmatmul__")
QDEF(MP_QSTR___rfloordiv__, (const byte*)"\x54\x98\x0d" "__rfloordiv__")
QDEF(MP_QSTR___rtruediv__, (const byte*)"\x5a\xd7\x0c" "__rtruediv__")
QDEF(MP_QSTR___rmod__, (const byte*)"\x31\x8a\x08" "__rmod__")
QDEF(MP_QSTR___rpow__, (const byte*)"\xff\x9a\x08" "__rpow__")
QDEF(MP_QSTR___ror__, (const byte*)"\x2a\xdc\x07" "__ror__")
QDEF(MP_QSTR___rxor__, (const byte*)"\xf2\x86\x08" "__rxor__")
QDEF(MP_QSTR___rand__, (const byte*)"\xdc\x2e\x08" "__rand__")
QDEF(MP_QSTR___rlshift__, (const byte*)"\x1b\xd1\x0b" "__rlshift__")
QDEF(MP_QSTR___rrshift__, (const byte*)"\xc5\x9d\x0b" "__rrshift__")
QDEF(MP_QSTR___dict__, (const byte*)"\x7f\x54\x08" "__dict__")
QDEF(MP_QSTR___get__, (const byte*)"\xb3\x8f\x07" "__get__")
QDEF(MP_QSTR___delete__, (const byte*)"\xdc\xed\x0a" "__delete__")
QDEF(MP_QSTR___set__, (const byte*)"\xa7\xb3\x07" "__set__")
QDEF(MP_QSTR___call__, (const byte*)"\xa7\xf9\x08" "__call__")
QDEF(MP_QSTR___iter__, (const byte*)"\xcf\x32\x08" "__iter__")
QDEF(MP_QSTR___bases__, (const byte*)"\x03\x30\x09" "__bases__")

QDEF(MP_QSTR__lt_module_gt_, (const byte*)"\xbd\x94\x08" "<module>")
QDEF(MP_QSTR__lt_lambda_gt_, (const byte*)"\x80\x8c\x08" "<lambda>")
QDEF(MP_QSTR__lt_listcomp_gt_, (const byte*)"\xd4\x15\x0a" "<listcomp>")
QDEF(MP_QSTR__lt_dictcomp_gt_, (const byte*)"\xcc\x8d\x0a" "<dictcomp>")
QDEF(MP_QSTR__lt_setcomp_gt_, (const byte*)"\x54\x51\x09" "<setcomp>")
QDEF(MP_QSTR__lt_genexpr_gt_, (const byte*)"\x34\x6a\x09" "<genexpr>")
QDEF(MP_QSTR__lt_string_gt_, (const byte*)"\x52\x53\x08" "<string>")
QDEF(MP_QSTR__lt_stdin_gt_, (const byte*)"\xe3\x63\x07" "<stdin>")
QDEF(MP_QSTR___contains__, (const byte*)"\xc6\x5f\x0c" "__contains__")

