/*
 * Copyright (c) 2006-2018, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2019-04-29     tyustli      first version
 */
// qstrs specific to this port
MP_QSTR_EPERM
MP_QSTR_ENOENT
MP_QSTR_EIO
MP_QSTR_EBADF
MP_QSTR_EAGAIN
MP_QSTR_ENOMEM
MP_QSTR_EACCES
MP_QSTR_EEXIST
MP_QSTR_ENODEV
MP_QSTR_EISDIR
MP_QSTR_EINVAL
MP_QSTR_EOPNOTSUPP
MP_QSTR_EADDRINUSE
MP_QSTR_ECONNABORTED
MP_QSTR_ECONNRESET
MP_QSTR_ENOBUFS
MP_QSTR_ENOTCONN
MP_QSTR_ETIMEDOUT
MP_QSTR_ECONNREFUSED
MP_QSTR_EHOSTUNREACH
MP_QSTR_EALREADY
MP_QSTR_EINPROGRESS,


